# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
      - master

permissions:
  actions: write
  checks:  write
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install The Environment
      run:  pip3 install requests  
    - name: SET Environment
      env:
         WEBHOOK_KEY:  ${{ secrets.WEBHOOK_KEY }}   
    - name: Run the Task For main ①
      run: python ./Src/main.py


